### ISSUE TITLE
dcc_challenge: AttributeError: 'FlightEnvVec' object has no attribute 'set_goal_position'

### ISSUE THREAD

**Issue by ouafi98** [uzh-rpg/flightmare#101]
I have run the file evaluation.py many times and I still get the same issue.

![issue](https://user-images.githubusercontent.com/43729232/112470350-d97f9900-8d6a-11eb-84c0-4bae99696813.png)

**Comment by ouafi98** [comment]
Please, does anyone has a solution?

**Comment by arsimone** [comment]
That was a typo, I just made two commits that slightly change the API of evaluation and obstacle_avoidance_agent, now it should work. Let me know if you have issue with that

**Comment by ouafi98** [comment]
Your changes are just "perfect". 
Thank a lot.
