### ISSUE TITLE
Communication Without Using Docker 

### ISSUE THREAD

**Issue by oggyfaker** [uzh-rpg/flightmare#102]
Hi , Thanks for your nice repo !
I have some problems with this source when i use docker to communicate with Unity . It's very hard to debug code and show the result or images to see. So do you have some way to compile it  without docker and how to connect port locally .

Hope to see your answer soon !

**Comment by yun-long** [comment]
Hi, you can follow the wiki on how to use Flightmare. 

In case you are using Flightmare for the DDC competition, you can check the installation guide on how to install Flightmare with pip. Make sure you also have also installed the prerequisites. 

https://github.com/uzh-rpg/flightmare/wiki/Prerequisites
https://github.com/uzh-rpg/flightmare/wiki/Install-with-pip
