### ISSUE TITLE
Unity standalone app has to be restarted every run of the python scripts

### ISSUE THREAD

**Issue by jhurlbut** [uzh-rpg/flightmare#105]
It's a minor inconvenience but I have to restart the standalone every time I run the training script. I am guessing maybe the socket is not getting cleanly disconnected from the Unity side when the script exits? It's not a showstopper but slows things down a bit. Thank you!

**Comment by arsimone** [comment]
It is meant to be like that. The standalone waits 120 seconds after receiving the last message from flightmare before resetting itself. It is done like that to handle random delay in the training phase.
