### ISSUE TITLE
Expected framerate for the Dodge Drones Challenge

### ISSUE THREAD

**Issue by alex-petrenko** [uzh-rpg/flightmare#106]
Hi there!
We've tried running the simulation without rendering (--render=0) and we're getting around 17000 FPS on our PC with a 1080Ti.
But when depth rendering is enabled, the FPS drops to around 350 FPS. Is this expected, or are we missing something?

Unity is being run with -batchmode

**Comment by yun-long** [comment]
Hi,

yes, this can happen. this is one of the main bottlenecks when using Unity&images. We are getting similar FPS on our machine.

**Comment by alex-petrenko** [comment]
Thank you!

**Comment by verma-rishabh** [comment]
Hi,
I am also getting similar fps with --render 1, but getting "Segmentation fault (core dumped)" while trying with --render 0,  running the example code (run_drone_control.py).
