### ISSUE TITLE
[ddc_challenge] index out of bound in high_level_planner.py

### ISSUE THREAD

**Issue by beniaminopozzan** [uzh-rpg/flightmare#126]
Hi,

in
https://github.com/uzh-rpg/flightmare/blob/5136d7239dd33a73158388216705666304734296/flightrl/rpg_baselines/evaluation/high_level_planner.py#L68-L69
when `num_run` is equal to `self.num_run-1` then `safe_num_run` becomes equal to `self.num_run` which is an invalid index for the fist axis of `self.goals_matrix`.

If the intent was to assign to `safe_num_run` the value `num_run+1` if it is a valid index and `num_run` otherwise, then I suggest to modify line 68 as following
`safe_num_run = (num_run + 1)*(num_run<(self.num_runs-1)) + num_run*(num_run==(self.num_runs-1))`

**Comment by antonilo** [comment]
@arsimone ptal

**Comment by antonilo** [comment]
Should be solved now, or is something missing?

**Comment by beniaminopozzan** [comment]
In my opinion, yes, it is.

**Comment by arsimone** [comment]
I agree
