### ISSUE TITLE
[ddc_challenge] episodes do not terminate when the last goal is reached

### ISSUE THREAD

**Issue by beniaminopozzan** [uzh-rpg/flightmare#127]
Hi,

in
https://github.com/uzh-rpg/flightmare/blob/5136d7239dd33a73158388216705666304734296/flightrl/rpg_baselines/evaluation/evaluation.py#L118-L145
when `done_from_high_level_planner` is equal to one the episode does not terminate immediately but it has to wait until `ep_len >= max_ep_length` becomes true. Is this the desired behavior?
If it is not, then the condition of the while
https://github.com/uzh-rpg/flightmare/blob/5136d7239dd33a73158388216705666304734296/flightrl/rpg_baselines/evaluation/evaluation.py#L119
should be
`not (done or done_from_high_level_planner or (ep_len >= max_ep_length))`

**Comment by antonilo** [comment]
Should be solved now, or is something missing?

**Comment by beniaminopozzan** [comment]
In my opinion, yes, it is.
