### ISSUE TITLE
Asking for a help about manual control

### ISSUE THREAD

**Issue by irfansamur** [uzh-rpg/flightmare#13]
I'm new to this stuffs. Can you send me a sample shortcode to control of this drone in python please?

**Comment by blu666** [comment]
Hey, I'm just learning this topic. Would you be able to provide some resources on controlling the drone? Many Thanks!

**Comment by cestbon1234** [comment]
I'm also learning about this topic. Would you share some code on how to control drones? Many thanks!

**Comment by amntheap** [comment]
I found out there might be an extra repo or probably some evaluation_node.py to help. Is it correct?
