### ISSUE TITLE
Build FlightGym error

### ISSUE THREAD

**Issue by hai-h-nguyen** [uzh-rpg/flightmare#14]
I got this error (Ubuntu 16.04):
``` /tmp/pip-req-build-t9aaza3_/include/flightlib/bridges/unity_bridge.hpp:12:27: fatal error: zmqpp/zmqpp.hpp: No such file or directory```.

What I should install to solve this?

**Comment by hai-h-nguyen** [comment]
Turn out, I had to install zmqpp https://github.com/zeromq/zmqpp

**Comment by arbaazkhan2** [comment]
Easier way to install zmqpp is to install from the Ubuntu source repository instead of the Github link(https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libzmqpp-dev_4.1.2-0ubuntu2_amd64.deb.html). (I couldn't get it to install from the github link)
