### ISSUE TITLE
Abandoned: 15 packages were abandoned. 

### ISSUE THREAD

**Issue by sotomotocross** [uzh-rpg/flightmare#15]
I followed the installation instructions https://github.com/uzh-rpg/flightmare/wiki/Install-with-ROS
but during the catkin build i had the attached errors.
![Screenshot from 2020-09-08 14-29-52](https://user-images.githubusercontent.com/23704278/92470971-dc0c0e00-f1df-11ea-855a-b2067f797b11.png)
![Screenshot from 2020-09-08 14-30-01](https://user-images.githubusercontent.com/23704278/92470974-dca4a480-f1df-11ea-9856-a1dd04efa035.png)

I have to point out that 15 packages were abandoned and 1 package failed.
What are the problems? What is missing?
Also i run: rosdep install --from-paths src --ignore-src -r -y
and #All required rosdeps installed succesfully

Thank you very much for the help.

**Comment by yun-long** [comment]
you are missing the `catkin_pkg` in your python. Try to install it via "(sudo) pip install catkin_pkg" or "pip3 install catkin_pkg". 

Or google the error message, **Import error, no module named "catkin_pkg"**. I believe you can find the answer.

**Comment by sotomotocross** [comment]
I have run all the commands you have told me.
Also I tried to run: sudo apt-get install python-catkin-pkg
In all cases the catkin_pkg is installed in the system.
Also googling the message didn't gave me any solutions.
Do you have any more propositions?
Thank you very much.

**Comment by yun-long** [comment]
Hmmm, it looks like a catkin/python/ROS problem. 

Did you build other ROS projects on your machine before?

**Comment by peasant98** [comment]
Hi @sotomotocross, do you get a new error after installing `catkin_pkg`? Or does `from catkin_pkg.package import parse_package` still cause an error?

**Comment by yun-long** [comment]
closing the issue. it seems like a ROS installation problem. feel free to reopen it if the issue still exists.

**Comment by sotomotocross** [comment]
Excuse me for the lack of feedback. I was with another project.
The error still exists. I tried to install the flightmare on a new Ubuntu 18.04.05 LTS system and i have the problem of the two attached screenshots.
![Screenshot from 2020-09-23 14-17-41](https://user-images.githubusercontent.com/23704278/94006232-34c6d380-fda8-11ea-8cc5-dbc34c5d39d4.png)
![Screenshot from 2020-09-23 14-18-00](https://user-images.githubusercontent.com/23704278/94006237-37c1c400-fda8-11ea-8b7b-69d3f1c7bc38.png)
I have installed the below:

1. sudo apt install python-catkin-pkg python-catkin-tools
2. pip install catkin-tools
3. pip install catkin-tools-python
4. sudo -H pip install -U catkin_pkg

Still the error doesn't stop appearing.
I have run catkin build before on this system and everything run ok. Especially earlier today i built https://github.com/uzh-rpg/rpg_esim that uses similar steps.

I don't know what else to do and i really need any help available.
Thank you in advance for the cooperation, time and help.
Looking forward to here from someone.

**Comment by vivekrathi14** [comment]
Initialize your build for python 2.7. It seems your catkin tools point to python 3.7.
Do this in your workspace directory (~/catkin_ws)
`catkin config --init --mkdirs --extend /opt/ros/$ROS_DISTRO --merge-devel --cmake-args -DCMAKE_BUILD_TYPE=Release -DPYTHON_VERSION=2.7`
