### ISSUE TITLE
Airsim instead of Unity

### ISSUE THREAD

**Issue by hai-h-nguyen** [uzh-rpg/flightmare#16]
How about using Airsim instead of Unity?

**Comment by peasant98** [comment]
Do you mean Unreal Engine @hai-h-nguyen? This repo is more of an alternative to using drones in Airsim.

**Comment by hai-h-nguyen** [comment]
Yeah, I mean using Unreal Engine. We are kind of having the whole scene in Airsim already but this repo comes out and it is promising. We don't want to rebuild the whole thing in Unity so I wonder if there is a way to utilize what we have in Airsim.

**Comment by peasant98** [comment]
Has the work you've done been tightly coupled with the Airsim environment (Unreal Engine, other Airsim related stuff)?

**Comment by peasant98** [comment]
@hai-h-nguyen

**Comment by yun-long** [comment]
Hi, It depends on your application. For machine learning applications, such as collect images with segmentation for training neural networks, AirSim might be better. In the cases of agile quadrotor fly, reinforcement learning, path planning, optimal control, you can consider using Flightmare. Check our paper for more details.    https://arxiv.org/abs/2009.00563

**Comment by hai-h-nguyen** [comment]
@peasant98 We decided to go with Airsim since we want to control directly from pixels. 
@yun-long  is the parallelism in this repo means running a scene with many drones? It is quite different from the parallelism in Gym.

**Comment by yun-long** [comment]
@hai-h-nguyen yes.
