### ISSUE TITLE
Extract the 3D point-cloud of the scene

### ISSUE THREAD

**Issue by pcarrascof** [uzh-rpg/flightmare#17]
I would like to know how to perform the extraction of 3D point-cloud.

And thank you very much for sharing your simulator.

**Comment by yun-long** [comment]
Hi, we will make the 3D point-cloud extraction available next week, with an example of how to use it.

**Comment by yun-long** [comment]
Hi @pcarrascof, please see https://github.com/uzh-rpg/flightmare/blob/master/flightlib/tests/bridges/unity_bridge.cpp#L27-L42
for an example on how to extract the point cloud.
