### ISSUE TITLE
RPG_Flightmare.x84-64 freeze with forest environment

### ISSUE THREAD

**Issue by patrickpoirier51** [uzh-rpg/flightmare#187]
Hello,

Downloaded and extracted RPG_Flightmare.x84-64  from here
https://github.com/uzh-rpg/flightmare/releases/latest

All other environments are working but Forest is freezing

I am running on  I7 with Nvidia 3080

**Comment by patrickpoirier51** [comment]
Well... I tested on a different computer and it works.... will dig into driver stuff and report back

**Comment by patrickpoirier51** [comment]
Yes confirmed, driver issues == fixed OK

**Comment by wuxinxin27** [comment]
I encountered the same problem, could you tell me how you solved it?
