### ISSUE TITLE
error: ‘CV_RGB2BGR’ was not declared in this scope

### ISSUE THREAD

**Issue by ghokulji** [uzh-rpg/flightmare#22]
![flightmare_build](https://user-images.githubusercontent.com/28822039/93314321-3c75fd80-f827-11ea-96fa-dfc7b1f6b21d.png)

I tried to build the new commit, the above error is showing. I included the '#include <opencv2/imgproc/types_c.h> in the unity_bridge.hpp' and it builds without any error. Is it the right way to fix the error?

**Comment by yun-long** [comment]
Hi @ghokulji , thanks for the feedback. 

I cannot reproduce the error. Which opencv version are you using?

**Comment by ghokulji** [comment]
Hey yun,
I am using opencv version 3.2.

**Comment by yun-long** [comment]
Hmmm, I am using the same OpenCV version. If it works, then I would say you are doing it right.

**Comment by Josias-C** [comment]
Getting the same error with opencv version 4.2.0. The mentioned fix worked for me too.
