### ISSUE TITLE
Running flightmare with px4 sitl 

### ISSUE THREAD

**Issue by sandeshthapa** [uzh-rpg/flightmare#28]

**Comment by sandeshthapa** [comment]
Hi, 

I'm running flightmare with ros and gazebo. I'm wondering if there is a way to run px4 sitl with flightmare.  If there is as way please, guide me. Thanks.

**Comment by yun-long** [comment]
HI,

Sorry, I don't know the answer to your question, since I personally don't use PX4 and am not familiar with PX4.

**Comment by Reka-Berci-Hajnovics** [comment]
Hi,
At our company, we are using ROS, Gazebo, and PX4 for all our drone-related simulations. The flightmare looks really amazing! It is a pity that it is not compatible with PX4. Are you considering connecting it with PX4? 
If not could you help with where to start to make it compatible?
