### ISSUE TITLE
How to add gates to Flightmare?

### ISSUE THREAD

**Issue by MajdWardeh** [uzh-rpg/flightmare#31]
Hello,

I would like to add gates to Flightmare just like to ones in the youtube video. Could you please tell me how to do that? I don't have any experience in Unity but I can learn.

Thank you,

**Comment by slimeth** [comment]
Hi,

You can spawn gates from the C++ side without knowledge about Unity. Check this code to see how to do it: https://github.com/uzh-rpg/flightmare/blob/master/flightlib/tests/bridges/unity_bridge.cpp#L163-L189

**Comment by MajdWardeh** [comment]
Awesome! Thank you!
