### ISSUE TITLE
How to get depth images for gym-style RL

### ISSUE THREAD

**Issue by junatcal** [uzh-rpg/flightmare#32]
I'm trying to train a policy to control a quadcopter in parallel using FlightEnvVec similarly to [run_drone_control](https://github.com/uzh-rpg/flightmare/blob/master/flightrl/examples/run_drone_control.py#L59). But I want to add depth image pixels as inputs (observations) to a policy.

How can I add depth images to observations and get observations with depth images from the python side for training? (I'm not using Gazebo, for parallelism.)

Thanks!

**Comment by yun-long** [comment]
Hi,

At the moment we don't provide python interface for retrieving images from Flihgmare, however, it is possible with the current setup

What you have to do is the following:

1. Create a quadrotor with a RGB camera, see https://github.com/uzh-rpg/flightmare/blob/master/flightlib/tests/bridges/unity_bridge.cpp#L75-L102
2. Create a pybind interface for image / depth,  similar to the `step function` https://github.com/uzh-rpg/flightmare/blob/master/flightlib/src/wrapper/pybind_wrapper.cpp#L22 
3. recompile and install flightgym
