### ISSUE TITLE
Connect with custom trajectory planner results in emergency landing protocol.

### ISSUE THREAD

**Issue by Stavya1993** [uzh-rpg/flightmare#44]
Been racking my head around it for quite some time. 
Just want to understand whats the logic behind the emergency landing protocol in flightmare so that I can edit it for my own use case.

**Comment by yun-long** [comment]
I guess this is because https://github.com/uzh-rpg/rpg_quadrotor_control, no sure what exactly is the problem, maybe you can provide more details.
