### ISSUE TITLE
Import error when python3 run_drone_control.py --train 1 in Ubuntu 20.04

### ISSUE THREAD

**Issue by BananaGorilla98** [uzh-rpg/flightmare#49]
Hi.

I am trying to run the fligtmare with `python3 run_drone_control.py --train 1` in `flightmare/flightrl/examples`. However, I got the import error. The detail of the error is here: 
![Screenshot from 2020-11-03 15-30-15](https://user-images.githubusercontent.com/54273658/97959054-81f78580-1de9-11eb-802a-2e8d4d0d3ac0.png)

I am trying to look for cuda-9 in my `/usr/local` but it is nowhere. 

May I know how to solve this problem?

**Comment by yun-long** [comment]
1. Make sure you followed this installation guide. In particular, was `cd flightlib && pip install .` success or not?
2. If you use `conda`, make sure you activate the conda environment.  `conda activate <env_name>`

**Comment by BananaGorilla98** [comment]
Yes. I followed the installation guide and the conda environment is activated. The `cd flightlib && pip install .` success too.
However, the problem is still there.

**Comment by yun-long** [comment]
Ok, I didn't read the error message. I misunderstood the problem. 
This is a TensorFlow or cuda problem. 

1. Do you have NVIDIA GPU on your laptop, if yes, follow the Tensorflow website on how to install the tensorflow-gpu properly. 
2. If no, simply install tensorflow without GPU support, `pip install tensorflow`

**Comment by peasant98** [comment]
Have you installed cuda 9 @BananaGorilla98?

**Comment by BananaGorilla98** [comment]
@yun-long Thanks for the suggested method. Would give a try to that solution and get back to you.
@peasant98 I don't have cuda 9 in my Ubuntu 20.04. Looks like it is Cuda 9 does not support on Ubuntu 20.04. Could other version of Cuda works?

**Comment by BananaGorilla98** [comment]
@yun-long Thanks for the efforts to help! I have sorted out the solution . :) Thank you once again.
