### ISSUE TITLE
Documentation on Specifics of Env

### ISSUE THREAD

**Issue by peasant98** [uzh-rpg/flightmare#58]
Hi, for the RL example, would you be able to provide some documentation on the specifications of the observation space and action space (of the env)? Thanks!

**Comment by yun-long** [comment]
Hi, we are working on the documentations. But you can still look into the code for more details about the observation space and action space. 

https://github.com/uzh-rpg/flightmare/blob/master/flightlib/include/flightlib/envs/quadrotor_env/quadrotor_env.hpp#L25-L39

In summary:
obs = [position, orientation, linear velocity, angular velocity] // full states of the quadrotor
act = [f1, f2, f3, f4] // thrusts of each propeller.

**Comment by peasant98** [comment]
Cool, thanks!
