### ISSUE TITLE
How many cameras it can support?

### ISSUE THREAD

**Issue by YiChenCityU** [uzh-rpg/flightmare#8]

**Comment by yun-long** [comment]
It supports multiple cameras, but you have to define the relative pose of each camera with respect to the center mass of the quadrotor. I might create an example about how to configure the stereo camera next week.

**Comment by YiChenCityU** [comment]
Thanks for your reply. Very interesting and useful project.

**Comment by phil333** [comment]
Hi @yun-long have you made an example for this? Are multiple cameras rendered in parallel or in sequence? I am wondering if multiple cameras are synchronized.
