### ISSUE TITLE
ddc_challenge : standalone.zip not found at url

### ISSUE THREAD

**Issue by jhurlbut** [uzh-rpg/flightmare#87]
there's no file at the url in the ddc_challenge docs on this page: https://github.com/uzh-rpg/flightmare/tree/ddc_challenge

http://rpg.ifi.uzh.ch/challenges/DodgeDrone2021/standalone.zip

**Comment by antonilo** [comment]
hi @jhurlbut, thank you very much for pointing that out! We have updated the readme to fix this issue
