### ISSUE TITLE
I get the following error when I do catkin_make in catkin_ws file after saving flightmare to the ruined catkin_ws / src directory. Can you help me?

### ISSUE THREAD

**Issue by 1617rosengineer** [uzh-rpg/flightmare#9]
CMake Error at flightmare/flightlib/cmake/catkin.cmake:2 (find_package):
  By not providing "Findcatkin_simple.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "catkin_simple", but CMake did not find one.

  Could not find a package configuration file provided by "catkin_simple"
  with any of the following names:

    catkin_simpleConfig.cmake
    catkin_simple-config.cmake

  Add the installation prefix of "catkin_simple" to CMAKE_PREFIX_PATH or set
  "catkin_simple_DIR" to a directory containing one of the above files.  If
  "catkin_simple" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  flightmare/flightlib/CMakeLists.txt:176 (include)

-- Configuring incomplete, errors occurred!
See also "/home/cansel/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/cansel/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:4324: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by yun-long** [comment]
I guess you forgot to do the `vcs-impoort < flightros/dependencies.yaml` under the catkin_ws/src directory.
